from solutions.logic.day_8 import get_number_of_antinodes


def test():
    puzzle_input = """............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............"""
    assert get_number_of_antinodes(puzzle_input) == 14


def test_part_two():
    puzzle_input = """............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............"""
    assert get_number_of_antinodes(puzzle_input, include_harmonics=True) == 34
